### ISSUE TITLE
GitHub Labs is dead. Long live GitHub Skills.

### ISSUE THREAD

**Issue by kenyachan** [uts-itd/getting-started#4]
There's a GitHub [blog post](https://github.blog/2022-06-06-introducing-github-skills/) about GitHub labs being shut down on 1 September 2022. Not all courses have been migrated over yet.

[GitHub Skills](https://skills.github.com/)

The following are available:
- Introduction to GitHub
- Review pull requests
- Resolve merge conflicts
- Hello GitHub Actions
- Continuous Integration

The following are not yet (as of 7 June 2022) available:
- Security strategy essentials
- Securing your workflows
- Creating a Release Based Workflow

**Comment by patrickkelso** [comment]
Somehow I missed this :( 

I'll fix this.
